# Generated by Django 3.2.24 on 2024-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XH_Forum_webapp', '0010_alter_contact_contacted_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.IntegerField(unique=True)),
                ('connection_id', models.CharField(max_length=255)),
            ],
        ),
    ]
