# Generated by Django 3.2.24 on 2024-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XH_Forum_webapp', '0012_userpublickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublickey',
            name='private_key',
            field=models.TextField(default='DEFAULT_PRIVATE_KEY_VALUE'),
        ),
    ]
