# Generated by Django 3.2.24 on 2024-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XH_Forum_webapp', '0016_post_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default='影评'),
        ),
    ]
